### ISSUE TITLE
Using in wordpress

### ISSUE THREAD

**Issue by jhdemicco** [brandoncordell/houzz-icon-font#1]
Not sure what I'm doing wrong. I was able to use this code in straight html with no problem, but couldn't seem to get it working in WordPress. I used an image for now but any help would be appreciated. Thanks!

**Comment by rtpHarry** [comment]
You haven't given enough detail to help with this I'm afraid. Is the site live somewhere? Can you explain:

1. how you put the files onto the web server
2. how you referenced the css file in your header
3. where you tried to use it

We might be able to get somewhere then :)

**Comment by jhdemicco** [comment]
Thanks for reaching out. Yes, the site is live at http://www.mosheaelyonstudio.com.

To answer your questions.

1. The files were uploaded via ftp
2. <link rel="stylesheet" href="http://www.mosheaelyonstudio.com/wp-content/themes/merapi-child/css/houzz-icon-font.css">
3. I've tried to use it all over the site. While I can get the logo to show up on a separate html page like http://mosheaelyonstudio.com/houzz-preview.html I can't get it to show up anywhere on the wordpress site itself. I've tried it in the header as well as in an individual page. Here is a link to a page with the same code as the html page and nothing shows up (http://mosheaelyonstudio.com/houzz-test/).

Thanks,

Jim

**Comment by jhdemicco** [comment]
Of course I figured it out 10 minutes after I sent this message. Turns out I needed to mark the   font-family: "houzz" !important; to keep it from being overridden. Thanks again for getting back to me. It was the kick in the butt to work on this again.

**Comment by brandoncordell** [comment]
@jhdemicco Glad you got it working! Sorry I didn't see this issue before.

@rtpHarry Thanks for helping!

Closing as resolved.
